### PR TITLE
Update the pink templates translation

### PR DESCRIPTION
**Pull request by minchao**

### CODE REVIEW

**Comment by satopian** [comment]
"Don't merge" Is it still a draft?
Ah, I intended to translate it into Traditional Chinese, but Simplified Chinese was in it. Excuse me.
Appropriate menu terms used on traditional Chinese bulletin boards are very helpful.

**Comment by minchao** [comment]
@satopian Yes, still a draft. I will check the translation again tomorrow and add more.

**Comment by minchao** [comment]
@satopian I think we can merge the current progress. The description of the paint mode will be further revised.

**Comment by satopian** [comment]
Thank you. After returning home, check a little more and merge.

**Pull request merged**
